export const ROUTE = {
  LOGIN_ROUTE: "v1/auth/sign-in",
  MARK_ATTENDENC: {
    CHECK_IN: "v1/attendance/check-in",
    CHECK_OUT: "v1/attendance/check-out",
  },
  ADD_CLIENT_ROUTE: "clients",
  CLIENTS: {
    GET: "v1/clients",
    UPDATE: "v1/clients",
    POST: "v1/clients",
    DELETE: "v1/clients",
    IMAGEPOST: "v1/client-documents",
    SEARCH: "v1/search",
    SHARE_PROFILE: "v1/share-profile",
    OPP_CLIENT_SEARCH: "v1/clients-search-profile",
  },
  ADD_FORM_ITEM: {
    GET: "v1/client-form-fields",
    UPDATE: "v1/client-form-fields",
    POST: "v1/client-form-fields",
    DELETE: "v1/client-form-fields",
  },
  MODULE: {
    ADD: "v1/modules",
    GET: "v1/modules",
    UPDATE: "v1/modules",
    DELETE: "v1/modules",
  },
  RELIGION: {
    ADD: "v1/religions",
    GET: "v1/religions",
    UPDATE: "v1/religions",
    DELETE: "v1/religions",
  },
  CASTE: {
    ADD: "v1/castes",
    GET: "v1/castes",
    UPDATE: "v1/castes",
    DELETE: "v1/castes",
  },
  SUB_CASTE: {
    ADD: "v1/sub-castes",
    GET: "v1/sub-castes",
    UPDATE: "v1/sub-castes",
    DELETE: "v1/sub-castes",
  },
  QUALIFICATION: {
    ADD: "v1/qualifications",
    GET: "v1/qualifications",
    UPDATE: "v1/qualifications",
    DELETE: "v1/qualifications",
  },
  VISA: {
    ADD: "v1/visas",
    GET: "v1/visas",
    UPDATE: "v1/visas",
    DELETE: "v1/visas",
  },
  OCCUPATION: {
    ADD: "v1/occupations",
    GET: "v1/occupations",
    UPDATE: "v1/occupations",
    DELETE: "v1/occupations",
  },
  SUB_OCCUPATION: {
    ADD: "v1/occupations",
    GET: "v1/occupations",
    UPDATE: "v1/occupations",
    DELETE: "v1/occupations",
  },
  COUNTRY: {
    ADD: "v1/countries",
    GET: "v1/countries",
    UPDATE: "v1/countries",
    DELETE: "v1/countries",
  },
  STATE: {
    ADD: "v1/states",
    GET: "v1/states",
    UPDATE: "v1/states",
    DELETE: "v1/states",
  },
  CITY: {
    ADD: "v1/cities",
    GET: "v1/cities",
    UPDATE: "v1/cities",
    DELETE: "v1/cities",
  },
  PREMIUM_COLLEGE: {
    ADD: "v1/premium-colleges",
    GET: "v1/premium-colleges",
    UPDATE: "v1/premium-colleges",
    DELETE: "v1/premium-colleges",
  },
  CLIENT_MODULE: {
    ADD: "v1/client/modules",
    GET: "v1/client/modules",
    UPDATE: "v1/client/modules",
    DELETE: "v1/client/modules",
  },
  PROFILE_SOURCE: {
    ADD: "v1/profile-sources",
    GET: "v1/profile-sources",
    UPDATE: "v1/profile-sources",
    DELETE: "v1/profile-sources",
  },
  MANAGE_USER: {
    ADD: "v1/users",
    GET: "v1/users",
    UPDATE: "v1/users",
    DELETE: "v1/users",
    GET_USER_BY_ID: "v1/users",
  },
  INCOME: {
    ADD: "v1/incomes",
    GET: "v1/incomes",
    UPDATE: "v1/incomes",
    DELETE: "v1/incomes",
  },
  LEAD_STATUS: {
    ADD: "v1/lead-statuses",
    GET: "v1/lead-statuses",
    UPDATE: "v1/lead-statuses",
    DELETE: "v1/lead-statuses",
  },
  MEMBERSHIP_PLAN: {
    ADD: "v1/membership-plans",
    GET: "v1/membership-plans",
    UPDATE: "v1/membership-plans",
    DELETE: "v1/membership-plans",
  },
  MEMBERSHIP_STATUS: {
    ADD: "v1/membership-statuses",
    GET: "v1/membership-statuses",
    UPDATE: "v1/membership-statuses",
    DELETE: "v1/membership-statuses",
  },
  MEMBERSHIP_TYPE: {
    ADD: "v1/membership-types",
    GET: "v1/membership-types",
    UPDATE: "v1/membership-types",
    DELETE: "v1/membership-types",
  },
  TASK_CATEGORY: {
    ADD: "v1/task-categories",
    GET: "v1/task-categories",
    UPDATE: "v1/task-categories",
    DELETE: "v1/task-categories",
  },
  PERMISSION: {
    GET: "v1/permissions",
  },
  ROLE: {
    ADD: "v1/roles",
    GET: "v1/roles",
    UPDATE: "v1/roles",
    DELETE: "v1/roles",
  },
  TASK: {
    ADD: "v1/tasks",
    GET: "v1/tasks",
    UPDATE: "v1/tasks",
    DELETE: "v1/tasks",
    ADD_CLIENT_Task: "v1/clients",
    GET_CLIENT_TASK: "v1/clients",
    DELETE_CLIENT_TASK: "v1/clients",
  },
  LEAD: {
    ADD: "v1/leads",
    GET: "v1/leads",
    UPDATE: "v1/leads",
    DELETE: "v1/leads",
    ADD_FOLLOW_UP: "v1/lead-followups",
    GET_FOLLOW_UP: "v1/lead-followups",
    UPDATE_FOLLOW_UP: "v1/lead-followups",
    DELETE_FOLLOW_UP: "v1/lead-followups",
    ASSIGN_LEADS: "v1/leads-assign",
  },
  CLIENT_RESPONSE: {
    ADD: "v1/client-responses",
    GET: "v1/client-responses",
    UPDATE: "v1/client-responses",
    DELETE: "v1/client-responses",
  },
  SHORT_LIST: {
    ADD: "v1/shortlists",
    GET: "v1/shortlists",
    UPDATE: "v1/shortlists",
    DELETE: "v1/shortlists",
    APPROVE_REJECT: "v1/shortlists/client",
  },
  CRM_SETTING: {
    ADD: "v1/crm-settings",
    GET: "v1/crm-settings",
    UPDATE: "v1/crm-settings",
    DELETE: "v1/crm-settings",
  },
  WHATSAPP_PROVIDER: {
    ADD: "v1/whatsapp-providers",
    GET: "v1/whatsapp-providers",
    UPDATE: "v1/whatsapp-providers",
    DELETE: "v1/whatsapp-providers",
  },
  WHATSAPP_KEY: {
    ADD: "v1/whatsapp-keys",
    GET: "v1/whatsapp-keys",
    UPDATE: "v1/whatsapp-keys",
    DELETE: "v1/whatsapp-keys",
  },
  PAYMENT: {
    GET: "v1/payments",
    ADD: "v1/payments",
    PUT: "v1/payments",
    DELETE: "v1/payments",
    PAYMENT_REPORT: "v1/payment-report",
  },
  EMAIL_TEMPLATE: {
    GET: "v1/email-templates",
    ADD: "v1/email-templates",
    PUT: "v1/email-templates",
    DELETE: "v1/email-templates",
  },
  WEBSITE_SETTINGS: {
    GET: "v1/website-settings",
    ADD: "v1/website-settings",
    PUT: "v1/website-settings",
    DELETE: "v1/website-settings",
  },
  ACTIVITY_LOG: {
    GET: "v1/activity-logs",
  },
  PDF_TEMPLATE: {
    GET: "v1/pdf-templates",
    ADD: "v1/pdf-templates",
    PUT: "v1/pdf-templates",
    DELETE: "v1/pdf-templates",
  },
  WHATSAPP_TEMPLATE: {
    GET: "v1/whatsapp-templates",
    ADD: "v1/whatsapp-templates",
    PUT: "v1/whatsapp-templates",
    DELETE: "v1/whatsapp-templates",
  },
  CLIENT_REPORT: {
    GET: "v1/client-report",
  },
  STAFF_REPORT: {
    GET: "v1/reports/staff",
  },
  ATTENDANC_REPORT: {
    GET: "v1/attendance-report",
    LOGGED_IN_USER: "v1/attendance/today-logged-in",
    LOGGED_OUT_USER: "v1/attendance/not-logged-in",
  },
  INTERACTION: {
    GET: "v1/interactions",
    ADD: "v1/interactions",
    PUT: "v1/interactions",
    DELETE: "v1/interactions",
  },
  TASK_FOLLOW_UP: {
    GET: "v1/task-followups",
    ADD: "v1/task-followups",
    PUT: "v1/task-followups",
    DELETE: "v1/task-followups",
  },
  DASHBOARD: {
    GET: "v1/dashboard/summary",
  },
};
