export const ROUTE = {
  LOGIN_ROUTE: "v1/auth/sign-in",
  ADD_CLIENT_ROUTE: "clients",
  ADD_FORM_ITEM: {
    GET: "v1/client-form-fields",
    UPDATE: "v1/client-form-fields",
    POST: "v1/client-form-fields",
    DELETE: "v1/client-form-fields",
  },
  MODULE: {
    ADD: "v1/modules",
    GET: "v1/modules",
    UPDATE: "v1/modules",
    DELETE: "v1/modules",
  },
  RELIGION: {
    ADD: "v1/religions",
    GET: "v1/religions",
    UPDATE: "v1/religions",
    DELETE: "v1/religions",
  },
  CASTE: {
    ADD: "v1/castes",
    GET: "v1/castes",
    UPDATE: "v1/castes",
    DELETE: "v1/castes",
  },
  SUB_CASTE: {
    ADD: "v1/sub-castes",
    GET: "v1/sub-castes",
    UPDATE: "v1/sub-castes",
    DELETE: "v1/sub-castes",
  },
  QUALIFICATION: {
    ADD: "v1/qualifications",
    GET: "v1/qualifications",
    UPDATE: "v1/qualifications",
    DELETE: "v1/qualifications",
  },
  VISA: {
    ADD: "v1/visas",
    GET: "v1/visas",
    UPDATE: "v1/visas",
    DELETE: "v1/visas",
  },
  OCCUPATION: {
    ADD: "v1/occupations",
    GET: "v1/occupations",
    UPDATE: "v1/occupations",
    DELETE: "v1/occupations",
  },
  SUB_OCCUPATION: {
    ADD: "v1/occupations",
    GET: "v1/occupations",
    UPDATE: "v1/occupations",
    DELETE: "v1/occupations",
  },
  COUNTRY: {
    ADD: "v1/countries",
    GET: "v1/countries",
    UPDATE: "v1/countries",
    DELETE: "v1/countries",
  },
  STATE: {
    ADD: "v1/states",
    GET: "v1/states",
    UPDATE: "v1/states",
    DELETE: "v1/states",
  },
  CITY: {
    ADD: "v1/cities",
    GET: "v1/cities",
    UPDATE: "v1/cities",
    DELETE: "v1/cities",
  },
  PREMIUM_COLLEGE: {
    ADD: "v1/premium-colleges",
    GET: "v1/premium-colleges",
    UPDATE: "v1/premium-colleges",
    DELETE: "v1/premium-colleges",
  },
  CLIENT_MODULE: {
    ADD: "v1/client/modules",
    GET: "v1/client/modules",
    UPDATE: "v1/client/modules",
    DELETE: "v1/client/modules",
  },
};
